const CONFIG={api:"https://script.google.com/macros/s/AKfycbxTzA1NS5Djj5334MBhe6bXEbRXBQqGg5D51nafUSRZWLbdKOCJhArfND4GyyoRpaG9/exec",sheetId:"1sNozbCN6Uy2CIgkCDlr8XO4Fv2VlXHuy7ybFY1OQbdE"};
const S={imovel:{},Prospeccao:[],Divulgacao:[],Contatos:[]};
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});document.querySelector("nav button").click();load()});
function api(action,p={}){return new Promise((ok,no)=>{let cb="cb"+Date.now();let s=document.createElement("script");window[cb]=x=>{delete window[cb];s.remove();ok(x)};s.onerror=()=>{delete window[cb];s.remove();no(Error("Falha no Apps Script"))};s.src=CONFIG.api+"?"+new URLSearchParams({action,callback:cb,...p});document.body.appendChild(s);setTimeout(()=>{if(window[cb]){delete window[cb];s.remove();no(Error("Tempo excedido"))}},15000)})}
async function write(action,p){await fetch(CONFIG.api,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({action,...p})})}
async function load(){try{let [i,p,d,c,t]=await Promise.all([api("getImovel"),api("list",{table:"Prospeccao"}),api("list",{table:"Divulgacao"}),api("list",{table:"Contatos"}),api("stats")]);S.imovel=i.data||{};S.Prospeccao=p.data||[];S.Divulgacao=d.data||[];S.Contatos=c.data||[];render(t.data||{});document.getElementById("status").textContent="Conectado"}catch(e){document.getElementById("status").textContent="Erro de conexão";alert(e.message)}}
function render(t){document.getElementById("stats").innerHTML=[["prospeccao","B2B"],["retornos","Retornos"],["interessados","Interessados"],["fechados","Fechados"]].map(x=>`<div class="card"><b>${t[x[0]]||0}</b>${x[1]}</div>`).join("");imovel();tab("pros","Prospeccao");tab("sites","Divulgacao");tab("contacts","Contatos");document.getElementById("b2b").value="Tenho uma casa mobiliada no Monte Sinai, Esmeraldas, disponível para alojamento temporário de equipe de obra. A localização é estratégica para Esmeraldas, Betim e Contagem. Trabalho com locação quinzenal ou mensal. Posso enviar fotos e condições.";document.getElementById("familia").value="Casa mobiliada disponível para estadia prolongada no Monte Sinai, Esmeraldas, com piscina, lago, churrasqueira, área gramada e estrutura completa. Disponível por quinzena ou mês."}
function imovel(){let f=[["localizacao","Localização"],["tipo","Tipo"],["quartos","Quartos"],["piscina","Piscina"],["lago","Lago"],["area_lazer","Área de lazer"],["gramado","Gramado"],["valor_mensal","Valor mensal"],["valor_quinzena","Valor quinzenal"],["estrategia_b2b","Estratégia B2B"],["estrategia_familia","Estratégia família"]];document.getElementById("imovelForm").innerHTML=f.map(x=>`<div class="field"><label>${x[1]}</label><input data-k="${x[0]}" value="${esc(S.imovel[x[0]]||"")}"></div>`).join("");document.getElementById("saveImovel").onclick=async()=>{let d={};document.querySelectorAll("[data-k]").forEach(x=>d[x.dataset.k]=x.value);await write("saveImovel",{data:JSON.stringify(d)});alert("Salvo");load()}}
function tab(id,t){document.getElementById(id).innerHTML=S[t].map((r,i)=>`<tr>${Object.keys(r).filter(k=>k!="_row").slice(0,5).map(k=>`<td>${esc(r[k])}</td>`).join("")}<td><button class="action" onclick="editar('${t}',${i})">Editar</button><button class="action" onclick="del('${t}',${i})">Excluir</button></td></tr>`).join("")||"<tr><td>Sem registros.</td></tr>"}
const fields={Prospeccao:["Empresa","Região","Segmento","Contato","Prioridade","Melhor abordagem","Mensagem específica","Observação","Status"],Divulgacao:["Canal","Modelo","Posicionamento","Prioridade","Melhor abordagem","Observação","Status","Link","Data da publicação","Próxima ação"],Contatos:["Data","Empresa/Pessoa","Canal","Tipo","Resultado","Valor proposto","Retorno em","Observação"]};
function novo(t){form(t,null)}
function editar(t,i){form(t,i)}
function form(t,i){let old=i===null?{}:S[t][i];document.getElementById("modal").hidden=false;document.getElementById("mt").textContent=i===null?"Novo registro":"Editar registro";document.getElementById("mf").innerHTML=fields[t].map(k=>`<div class="${k=="Melhor abordagem"||k=="Mensagem específica"||k=="Observação"||k=="Resultado"||k=="Posicionamento"?"field full":"field"}"><label>${k}</label>${["Melhor abordagem","Mensagem específica","Observação","Resultado","Posicionamento"].includes(k)?`<textarea name="${k}">${esc(old[k]||"")}</textarea>`:`<input name="${k}" value="${esc(old[k]||"")}">`}</div>`).join("")+`<button>Salvar</button>`;document.getElementById("mf").onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(i!==null)d._row=old._row;await write(i===null?"insert":"update",{table:t,data:JSON.stringify(d)});fechar();setTimeout(load,700)}}
async function del(t,i){if(confirm("Excluir?")){await write("delete",{table:t,row:S[t][i]._row});setTimeout(load,700)}}
function fechar(){document.getElementById("modal").hidden=true}function copiar(id){navigator.clipboard.writeText(document.getElementById(id).value);alert("Copiado")}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}